local IdleSite = {
		{
			Id = 1,
			cityId = 1001,
			name = "糖葫芦驿站",
			desc = "地道的北京小吃，总有一种适合你！",
			isLock = False,
			unlockPrice = "1,0",
			itemId = 1,
			siteBaseLv = 1,
			siteBase = "IdleSiteBase1",
			siteGrade = "IdleSiteGrade1",
			siteTimeLv = 1,
			siteTime = "IdleSiteTime1",
			siteVolumeLv = 1,
			siteVolume = "IdleSiteVolume1",
			image = "siteIcon1",
			posX = -3.53,
			posY = -11.16,
			size = 6.8,
		},
		{
			Id = 2,
			cityId = 1001,
			name = "古书驿站",
			desc = "为过万游客运送各类图书！",
			isLock = True,
			unlockPrice = "30000,0",
			itemId = 1,
			siteBaseLv = 1,
			siteBase = "IdleSiteBase2",
			siteGrade = "IdleSiteGrade2",
			siteTimeLv = 1,
			siteTime = "IdleSiteTime2",
			siteVolumeLv = 1,
			siteVolume = "IdleSiteVolume2",
			image = "siteIcon2",
			posX = 9.37,
			posY = -19.07,
			size = 6.8,
		},
		{
			Id = 3,
			cityId = 1001,
			name = "潮玩驿站",
			desc = "年轻人的文化圣地！一起High！",
			isLock = True,
			unlockPrice = "800000,0",
			itemId = 2,
			siteBaseLv = 1,
			siteBase = "IdleSiteBase3",
			siteGrade = "IdleSiteGrade3",
			siteTimeLv = 1,
			siteTime = "IdleSiteTime3",
			siteVolumeLv = 1,
			siteVolume = "IdleSiteVolume3",
			image = "siteIcon3",
			posX = 20.1,
			posY = -26.1,
			size = 6.8,
		},
		{
			Id = 4,
			cityId = 1001,
			name = "医疗驿站",
			desc = "医疗资源专线，保证充足的供应！",
			isLock = True,
			unlockPrice = "30000000,0",
			itemId = 2,
			siteBaseLv = 1,
			siteBase = "IdleSiteBase4",
			siteGrade = "IdleSiteGrade4",
			siteTimeLv = 1,
			siteTime = "IdleSiteTime4",
			siteVolumeLv = 1,
			siteVolume = "IdleSiteVolume4",
			image = "siteIcon4",
			posX = 6.7,
			posY = -6.5,
			size = 6.8,
		},
		{
			Id = 5,
			cityId = 1001,
			name = "家禽驿站",
			desc = "老北京烤鸭，你值得拥有！",
			isLock = True,
			unlockPrice = "20000000,2",
			itemId = 3,
			siteBaseLv = 1,
			siteBase = "IdleSiteBase5",
			siteGrade = "IdleSiteGrade5",
			siteTimeLv = 1,
			siteTime = "IdleSiteTime5",
			siteVolumeLv = 1,
			siteVolume = "IdleSiteVolume5",
			image = "siteIcon5",
			posX = 16.27,
			posY = -13.08,
			size = 6.8,
		},
		{
			Id = 6,
			cityId = 1001,
			name = "文玩驿站",
			desc = "古玩字画一元起！走一走看一看了啊！",
			isLock = True,
			unlockPrice = "30000000,4",
			itemId = 3,
			siteBaseLv = 1,
			siteBase = "IdleSiteBase6",
			siteGrade = "IdleSiteGrade6",
			siteTimeLv = 1,
			siteTime = "IdleSiteTime6",
			siteVolumeLv = 1,
			siteVolume = "IdleSiteVolume6",
			image = "siteIcon6",
			posX = 26.18,
			posY = -5.5,
			size = 6.8,
		},
}
return IdleSite