local IdleSiteGrade6 = {
		{
			Id = 1,
			lvmin = 1,
			lvmax = 24,
			multiple = 1.5,
			totalmultiple = "1,0",
			image = "siteIcon3",
			staffnum = 1,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = -1,
		},
		{
			Id = 2,
			lvmin = 25,
			lvmax = 49,
			multiple = 1.5,
			totalmultiple = "1.5,0",
			image = "siteIcon3",
			staffnum = 1,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 0,
		},
		{
			Id = 3,
			lvmin = 50,
			lvmax = 74,
			multiple = 1.5,
			totalmultiple = "2.25,0",
			image = "siteIcon3",
			staffnum = 1,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 1,
		},
		{
			Id = 4,
			lvmin = 75,
			lvmax = 99,
			multiple = 1.6,
			totalmultiple = "3.38,0",
			image = "siteIcon3",
			staffnum = 2,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 2,
		},
		{
			Id = 5,
			lvmin = 100,
			lvmax = 149,
			multiple = 1.8,
			totalmultiple = "5.4,0",
			image = "siteIcon3",
			staffnum = 2,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 3,
		},
		{
			Id = 6,
			lvmin = 150,
			lvmax = 199,
			multiple = 2,
			totalmultiple = "9.72,0",
			image = "siteIcon3",
			staffnum = 2,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 4,
		},
		{
			Id = 7,
			lvmin = 200,
			lvmax = 299,
			multiple = 2,
			totalmultiple = "19.44,0",
			image = "siteIcon3",
			staffnum = 3,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 5,
		},
		{
			Id = 8,
			lvmin = 300,
			lvmax = 399,
			multiple = 2,
			totalmultiple = "38.88,0",
			image = "siteIcon3",
			staffnum = 3,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 6,
		},
		{
			Id = 9,
			lvmin = 400,
			lvmax = 499,
			multiple = 2,
			totalmultiple = "77.76,0",
			image = "siteIcon3",
			staffnum = 3,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 7,
		},
		{
			Id = 10,
			lvmin = 500,
			lvmax = 599,
			multiple = 3,
			totalmultiple = "155.52,0",
			image = "siteIcon3",
			staffnum = 4,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 8,
		},
		{
			Id = 11,
			lvmin = 600,
			lvmax = 699,
			multiple = 3,
			totalmultiple = "466.56,0",
			image = "siteIcon3",
			staffnum = 4,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 9,
		},
		{
			Id = 12,
			lvmin = 700,
			lvmax = 799,
			multiple = 3,
			totalmultiple = "1399.68,0",
			image = "siteIcon3",
			staffnum = 4,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 10,
		},
		{
			Id = 13,
			lvmin = 800,
			lvmax = 899,
			multiple = 6,
			totalmultiple = "4199.04,0",
			image = "siteIcon3",
			staffnum = 5,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 11,
		},
		{
			Id = 14,
			lvmin = 900,
			lvmax = 999,
			multiple = 8,
			totalmultiple = "25194.24,0",
			image = "siteIcon3",
			staffnum = 5,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 12,
		},
		{
			Id = 15,
			lvmin = 1000,
			lvmax = 1249,
			multiple = 10,
			totalmultiple = "201553.92,0",
			image = "siteIcon3",
			staffnum = 5,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 13,
		},
		{
			Id = 16,
			lvmin = 1250,
			lvmax = 1499,
			multiple = 15,
			totalmultiple = "2015539.2,0",
			image = "siteIcon3",
			staffnum = 6,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 14,
		},
		{
			Id = 17,
			lvmin = 1500,
			lvmax = 1749,
			multiple = 20,
			totalmultiple = "30233088,0",
			image = "siteIcon3",
			staffnum = 6,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 15,
		},
		{
			Id = 18,
			lvmin = 1750,
			lvmax = 1999,
			multiple = 24,
			totalmultiple = "60466176,1",
			image = "siteIcon3",
			staffnum = 6,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 16,
		},
		{
			Id = 19,
			lvmin = 2000,
			lvmax = 2249,
			multiple = 28,
			totalmultiple = "14511882.24,3",
			image = "siteIcon3",
			staffnum = 7,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 17,
		},
		{
			Id = 20,
			lvmin = 2250,
			lvmax = 2499,
			multiple = 32,
			totalmultiple = "40633270.27,4",
			image = "siteIcon3",
			staffnum = 7,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 18,
		},
		{
			Id = 21,
			lvmin = 2500,
			lvmax = 2749,
			multiple = 36,
			totalmultiple = "13002646.49,6",
			image = "siteIcon3",
			staffnum = 8,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 19,
		},
		{
			Id = 22,
			lvmin = 2750,
			lvmax = 2999,
			multiple = 40,
			totalmultiple = "46809527.35,7",
			image = "siteIcon3",
			staffnum = 8,
			staffRes = nil,
			prefabName = "wenwan_lv2",
			itemIndex = 20,
		},
}
return IdleSiteGrade6