local IdleTruckRes = {
		{
			Id = 1,
			lvmin = 1,
			lvmax = 1,
			icon = nil,
			spriteUp = "truck_lv01_up_1",
			spriteDown = "truck_lv01_down_1",
			emptySpriteUp = "truck_lv01_up_0",
			emptySpriteDown = "truck_lv01_down_0",
		},
		{
			Id = 2,
			lvmin = 2,
			lvmax = 2,
			icon = nil,
			spriteUp = "truck_lv02_up_1",
			spriteDown = "truck_lv02_down_1",
			emptySpriteUp = "truck_lv02_up_0",
			emptySpriteDown = "truck_lv02_down_0",
		},
		{
			Id = 3,
			lvmin = 3,
			lvmax = 3,
			icon = nil,
			spriteUp = "truck_lv02_up_1",
			spriteDown = "truck_lv02_down_1",
			emptySpriteUp = "truck_lv02_up_0",
			emptySpriteDown = "truck_lv02_down_0",
		},
		{
			Id = 4,
			lvmin = 4,
			lvmax = 4,
			icon = nil,
			spriteUp = "truck_lv03_up_1",
			spriteDown = "truck_lv03_down_1",
			emptySpriteUp = "truck_lv03_up_0",
			emptySpriteDown = "truck_lv03_down_1",
		},
		{
			Id = 5,
			lvmin = 5,
			lvmax = 5,
			icon = nil,
			spriteUp = "truck_lv03_up_1",
			spriteDown = "truck_lv03_down_1",
			emptySpriteUp = "truck_lv03_up_0",
			emptySpriteDown = "truck_lv03_down_1",
		},
		{
			Id = 6,
			lvmin = 6,
			lvmax = 6,
			icon = nil,
			spriteUp = "truck_lv04_up_1",
			spriteDown = "truck_lv04_down_1",
			emptySpriteUp = "truck_lv04_up_0",
			emptySpriteDown = "truck_lv04_down_0",
		},
		{
			Id = 7,
			lvmin = 7,
			lvmax = 7,
			icon = nil,
			spriteUp = "truck_lv04_up_1",
			spriteDown = "truck_lv04_down_1",
			emptySpriteUp = "truck_lv04_up_0",
			emptySpriteDown = "truck_lv04_down_0",
		},
		{
			Id = 8,
			lvmin = 8,
			lvmax = 8,
			icon = nil,
			spriteUp = "truck_lv05_up_1",
			spriteDown = "truck_lv05_down_1",
			emptySpriteUp = "truck_lv05_up_0",
			emptySpriteDown = "truck_lv05_down_1",
		},
		{
			Id = 9,
			lvmin = 9,
			lvmax = 9,
			icon = nil,
			spriteUp = "truck_lv05_up_1",
			spriteDown = "truck_lv05_down_1",
			emptySpriteUp = "truck_lv05_up_0",
			emptySpriteDown = "truck_lv05_down_1",
		},
		{
			Id = 10,
			lvmin = 10,
			lvmax = 10,
			icon = nil,
			spriteUp = "truck_lv05_up_1",
			spriteDown = "truck_lv05_down_1",
			emptySpriteUp = "truck_lv05_up_0",
			emptySpriteDown = "truck_lv05_down_1",
		},
}
_G.IdleTruckRes = IdleTruckRes
setmetatable(_G,IdleTruckRes)
return IdleTruckRes