local IdleSiteGrade3 = {
		{
			Id = 1,
			lvmin = 1,
			lvmax = 24,
			multiple = 1.3,
			totalmultiple = "1,0",
			image = "siteIcon4",
			staffnum = 1,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = -1,
		},
		{
			Id = 2,
			lvmin = 25,
			lvmax = 49,
			multiple = 1.4,
			totalmultiple = "1.3,0",
			image = "siteIcon4",
			staffnum = 1,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 0,
		},
		{
			Id = 3,
			lvmin = 50,
			lvmax = 74,
			multiple = 1.5,
			totalmultiple = "1.82,0",
			image = "siteIcon4",
			staffnum = 1,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 1,
		},
		{
			Id = 4,
			lvmin = 75,
			lvmax = 99,
			multiple = 1.6,
			totalmultiple = "2.73,0",
			image = "siteIcon4",
			staffnum = 2,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 2,
		},
		{
			Id = 5,
			lvmin = 100,
			lvmax = 149,
			multiple = 1.8,
			totalmultiple = "4.37,0",
			image = "siteIcon4",
			staffnum = 2,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 3,
		},
		{
			Id = 6,
			lvmin = 150,
			lvmax = 199,
			multiple = 2,
			totalmultiple = "7.86,0",
			image = "siteIcon4",
			staffnum = 2,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 4,
		},
		{
			Id = 7,
			lvmin = 200,
			lvmax = 299,
			multiple = 2,
			totalmultiple = "15.72,0",
			image = "siteIcon4",
			staffnum = 3,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 5,
		},
		{
			Id = 8,
			lvmin = 300,
			lvmax = 399,
			multiple = 2,
			totalmultiple = "31.45,0",
			image = "siteIcon4",
			staffnum = 3,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 6,
		},
		{
			Id = 9,
			lvmin = 400,
			lvmax = 499,
			multiple = 2,
			totalmultiple = "62.9,0",
			image = "siteIcon4",
			staffnum = 3,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 7,
		},
		{
			Id = 10,
			lvmin = 500,
			lvmax = 599,
			multiple = 3,
			totalmultiple = "125.8,0",
			image = "siteIcon4",
			staffnum = 4,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 8,
		},
		{
			Id = 11,
			lvmin = 600,
			lvmax = 699,
			multiple = 3,
			totalmultiple = "377.4,0",
			image = "siteIcon4",
			staffnum = 4,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 9,
		},
		{
			Id = 12,
			lvmin = 700,
			lvmax = 799,
			multiple = 3,
			totalmultiple = "1132.19,0",
			image = "siteIcon4",
			staffnum = 4,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 10,
		},
		{
			Id = 13,
			lvmin = 800,
			lvmax = 899,
			multiple = 4,
			totalmultiple = "3396.56,0",
			image = "siteIcon4",
			staffnum = 5,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 11,
		},
		{
			Id = 14,
			lvmin = 900,
			lvmax = 999,
			multiple = 5,
			totalmultiple = "13586.23,0",
			image = "siteIcon4",
			staffnum = 5,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 12,
		},
		{
			Id = 15,
			lvmin = 1000,
			lvmax = 1249,
			multiple = 8,
			totalmultiple = "67931.14,0",
			image = "siteIcon4",
			staffnum = 5,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 13,
		},
		{
			Id = 16,
			lvmin = 1250,
			lvmax = 1499,
			multiple = 10,
			totalmultiple = "543449.09,0",
			image = "siteIcon4",
			staffnum = 6,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 14,
		},
		{
			Id = 17,
			lvmin = 1500,
			lvmax = 1749,
			multiple = 13,
			totalmultiple = "5434490.88,0",
			image = "siteIcon4",
			staffnum = 6,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 15,
		},
		{
			Id = 18,
			lvmin = 1750,
			lvmax = 1999,
			multiple = 20,
			totalmultiple = "70648381.44,0",
			image = "siteIcon4",
			staffnum = 6,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 16,
		},
		{
			Id = 19,
			lvmin = 2000,
			lvmax = 2249,
			multiple = 22,
			totalmultiple = "14129676.29,2",
			image = "siteIcon4",
			staffnum = 7,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 17,
		},
		{
			Id = 20,
			lvmin = 2250,
			lvmax = 2499,
			multiple = 24,
			totalmultiple = "31085287.83,3",
			image = "siteIcon4",
			staffnum = 7,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 18,
		},
		{
			Id = 21,
			lvmin = 2500,
			lvmax = 2749,
			multiple = 26,
			totalmultiple = "74604690.8,4",
			image = "siteIcon4",
			staffnum = 8,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 19,
		},
		{
			Id = 22,
			lvmin = 2750,
			lvmax = 2999,
			multiple = 36,
			totalmultiple = "19397219.61,6",
			image = "siteIcon4",
			staffnum = 8,
			staffRes = nil,
			prefabName = "chuangyiyuan_lv1",
			itemIndex = 20,
		},
}
_G.IdleSiteGrade3 = IdleSiteGrade3
return IdleSiteGrade3