local IdleGuideStep = {
		{
			Id = 101,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "欢迎你，老板！我们的<color=\"#E8711A\"><size=48>快递公司</size></color>开业啦，快看！我们的第一批<color=\"#E8711A\"><size=48>快递</size></color>送来了！",
			PauseGame = True,
			Finger = 1,
		},
		{
			Id = 102,
			ActionType = 3,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = False,
			NeedFollowTarget = True,
			ParentTransName = "map/sky/idleCityTruck.prefab",
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 103,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "这里是<color=\"#E8711A\"><size=48>快递总站</size></color>，叉车司机会把快递卸到<color=\"#E8711A\"><size=48>货架</size></color>上。",
			PauseGame = True,
			Finger = 1,
		},
		{
			Id = 104,
			ActionType = 3,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = False,
			NeedFollowTarget = True,
			ParentTransName = "map/mid/citystaff_1_0",
			TargetTransName = nil,
			UIItemIndex = nil,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 105,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "分发员会将快递从货架处送给<color=\"#E8711A\"><size=48>配送员</size></color>。",
			PauseGame = True,
			Finger = 1,
		},
		{
			Id = 106,
			ActionType = 3,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = False,
			NeedFollowTarget = True,
			ParentTransName = "map/mid/Prefabs_Idle_truck.prefab",
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 107,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "很好，接下来将由配送员把快递送到<color=\"#E8711A\"><size=48>驿站</size></color>。",
			PauseGame = True,
			Finger = 1,
		},
		{
			Id = 108,
			ActionType = 3,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = False,
			NeedFollowTarget = True,
			ParentTransName = "map/group5/mid/yiyuan (1)/Prefabs_Idle_remover.prefab",
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 109,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "工作人员将快递揽收到驿站，后面由<color=\"#E8711A\"><size=48>快递小哥</size></color>将货物分发出去。",
			PauseGame = True,
			Finger = 1,
		},
		{
			Id = 110,
			ActionType = 3,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = False,
			NeedFollowTarget = True,
			ParentTransName = "map/group5/mid/yiyuan (1)/Prefabs_Idle_staff1.prefab",
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 111,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "恭喜老板，你赚到了第一桶金，<color=\"#E8711A\"><size=48>升级驿站</size></color>，提升赚钱效率吧。",
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 112,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = True,
			NeedFollowTarget = False,
			ParentTransName = "map/group5/mid/yiyuan (1)",
			TargetTransName = "collider",
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 113,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 9,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = "UIContent/IdleWindow(Clone)/IdlePostSiteWindow(Clone)/bg/content/updagradePostSiteBg",
			TargetTransName = "btn-upgradePostSite",
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 201,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "很好，升级驿站后，公司赚钱效率大幅提升了。<color=\"#E8711A\"><size=48>升级驿站</size></color>，<color=\"#E8711A\"><size=48>升级驿站</size></color>，<color=\"#E8711A\"><size=48>升级驿站</size></color>，重要的事情重复三遍！",
			PauseGame = True,
			Finger = 1,
		},
		{
			Id = 202,
			ActionType = 3,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = True,
			NeedFollowTarget = False,
			ParentTransName = "map/group0/build/kuaidizhongxin/deliverySiteCollider",
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 203,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "想要扩大规模，记得升级<color=\"#E8711A\"><size=48>快递中心</size></color>，全城的货物都会先在这里集中起来，容量越大，生意越大。",
			PauseGame = True,
			Finger = 1,
		},
		{
			Id = 204,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = True,
			NeedFollowTarget = False,
			ParentTransName = "map/group0/build/kuaidizhongxin",
			TargetTransName = "deliverySiteCollider",
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 205,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 2,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = "UIContent/IdleWindow(Clone)/IdleSiteInfoWindow(Clone)/bg/content/siteVolume/siteVolumeBg",
			TargetTransName = "btn-upgradeSiteVolume",
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 206,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 1,
			Delay = 1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = "UIContent/IdleWindow(Clone)/IdleSiteInfoWindow(Clone)/bg/content/storeVolume/siteSpeedBg",
			TargetTransName = "btn-upgradeStoreSpeed",
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 301,
			ActionType = 3,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = True,
			NeedFollowTarget = False,
			ParentTransName = "map/group0/build/truckStation/truckSiteCollider",
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 302,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "想要提高运输效率，记得升级<color=\"#E8711A\"><size=48>停车场</size></color>，解锁更多快递员，人多力量大。",
			PauseGame = True,
			Finger = 1,
		},
		{
			Id = 303,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = True,
			NeedFollowTarget = False,
			ParentTransName = "map/group0/build/truckStation",
			TargetTransName = "truckSiteCollider",
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 304,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = "UIContent/IdleWindow(Clone)/IdleTruckInfoWindow(Clone)/bg/content/truckUpgradeNode/updradeVolumeBg",
			TargetTransName = "btn-upgradeVolume",
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 305,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = True,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = "UIContent/IdleWindow(Clone)/IdleTruckInfoWindow(Clone)/bg/content/truckUpgradeNode/upgradeCountbg",
			TargetTransName = "btn-upgradeCount",
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 306,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "太棒了！老板，公司的发展就拜托您了！想知道下一步做什么，可以点击<color=\"#E8711A\"><size=48>左下角的任务</size></color>，随时听候您的差遣！",
			PauseGame = True,
			Finger = 1,
		},
		{
			Id = 401,
			ActionType = 1,
			EndCondition = -1,
			ClickCount = -1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = nil,
			TargetTransName = nil,
			UIItemIndex = -1,
			TipKey = "恭喜老板，你可以解锁<color=\"#E8711A\"><size=48>第二个驿站</size></color>了，我们的生意越做越大了！",
			PauseGame = True,
			Finger = 1,
		},
		{
			Id = 402,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = "UIContent/IdleWindow(Clone)/menuBtns",
			TargetTransName = "btn-build",
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 403,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = True,
			NeedFocus = False,
			NeedFollowTarget = False,
			ParentTransName = "UIContent/IdleWindow(Clone)/IdleBuildingWindow(Clone)/bg/sitesScrollView/Viewport/Content",
			TargetTransName = "postSiteInfoNode/btn-build",
			UIItemIndex = 1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
		{
			Id = 404,
			ActionType = 2,
			EndCondition = -1,
			ClickCount = 1,
			Delay = -1,
			CloseWindow = False,
			IsUI = False,
			NeedFocus = True,
			NeedFollowTarget = False,
			ParentTransName = "map/group1/mid/lou_kaoya (1)",
			TargetTransName = "collider",
			UIItemIndex = -1,
			TipKey = nil,
			PauseGame = False,
			Finger = 1,
		},
}
_G.IdleGuideStep = IdleGuideStep
return IdleGuideStep